config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/index'

  get 'about', to: 'home#about', as: :about

  get 'movies/:id/rating', to: 'movies#rating', as: :movie_rating

  get 'movies/:id/reviews', to: 'movies#reviews', as: :movie_reviews

  get 'movies/:movie_id/:movie_title/reviews/new', to: 'reviews#new', as: :new_movie_review

  resources :movies, only: [:index, :show]
  
  resources :reviews, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
    #Make sure we can't create a review without email, rating, or movie
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :rating, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
    validates :movie_id, numericality: true

    #Get The five most recently reviewed movies in DB
    def self.get_five_most_recently_reviewed_movies
        movies = Review.select('MAX(created_at) as created_at, movie_title, movie_id, avg(rating) as rating').group(:movie_id, :movie_title).order("created_at desc").limit(5)

        return movies
    end

    #Get the five most recent reviews with comments in DB
    def self.get_five_most_recent_reviews
        reviews = Review.where("comment <> ''").limit(5).order('created_at desc')
        
        return reviews
    end

    #Get a movie's average rating by id
    def self.get_average_rating(id)
        rating = Review.where('movie_id = ?', id).average(:rating)
        return rating
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #Grab most recent reviews and movies from DB to populate homepage
    @recent_reviews = Review.get_five_most_recent_reviews
    @recent_movies = Review.get_five_most_recently_reviewed_movies
  end

  def about
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  end

  def show
    #Grab reviews for given movie_id to populate page
    @movie_id = params[:id]
    @reviews = Review.where(:movie_id => @movie_id).order('created_at desc')
  end

  def rating
    #Send average rating for a movie as plaintext
    render plain: Review.get_average_rating(params[:id])
  end

  def reviews
    #Send First three reviews for a given movie ID as json
    render :json => {:reviews => Review.where(:movie_id => params[:id]).order('created_at desc').limit(3)}
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    #Grab all reviews to populate page
    @reviews = Review.order('created_at desc')
  end

  def new
    #Get movie_id, title, and new Review for new page
    @movie_id = params[:movie_id]
    @movie_title = params[:movie_title]
    @review = Review.new
  end

  def create
    #Using returned parameters, create a new review
    @review = Review.new(params.require(:review).permit(:email, :rating, :comment, :movie_id, :movie_title))

    #If review was saved, send to Movie path with proper notice
    #Otherwise, send back to new movie path with proper notice
    if @review.save
      flash[:primary] = "Your review was saved"
      redirect_to movie_path(@review.movie_id)
    else
      flash[:warning] = "There was a problem saving your review"
      redirect_to new_movie_review_path(:movie_id => @review.movie_id, :movie_title => @review.movie_title)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/_movie.html.erb
<div class="card text-white bg-secondary mt-3">
                <div class="row">
                    <div class="col-3 m-3 no-gutter">
                        <%= image_tag movie.image_location, size: '150x150'%>
                        <br />
                        <% (1..5).each do |i| %>
                            <% if movie.rating >= i %>
                                <%= image_tag "star-filled.png", size: '25x25', class: "m-0 p-0 mb-3" %>
                            <% else %>
                                <%= image_tag "star-empty.png", size: '25x25', class: "m-0 p-0 mb-3" %>
                            <% end %>
                        <% end %>
                    </div>
                    <div class="col">
                        <div class="card-body">
                            <%= link_to movie.title, movie_path(:id => movie.id), class: "h4 text-white" %>
                            <p class="card-text">
                            Release date: <%= movie.release_date %>
                            <br />
                            Genres: <%= movie.genres.join(", ") %>
                            </p>
                            <div id="review-section"></div>
                            <div class="row">
                                <%= link_to "View More Reviews", movie_path(:id => movie.id), class: "text-white mr-3" %>
                                <%= link_to "Write A Review", new_movie_review_path(:movie_id => movie.id), class: "text-white" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

app/views/home/_recent_movie.html.erb
 <div class="row">
    <div class="col">
        <p class="card-text mb-2 ml-1">
            <%= link_to recent_movie.movie_title, movie_path(recent_movie.movie_id), class: "text-white" %>
        </p>
    </div>
    <div class="col ml-auto">
        <% (1..5).each do |i| %>
            <% if recent_movie.rating >= i %>
                <%= image_tag "star-filled.png", size: '20x20', class: "m-0 p-0 mb-2" %>
            <% else %>
                <%= image_tag "star-empty.png", size: '20x20', class: "m-0 p-0 mb-2" %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/home/_recent_review.html.erb
<div class="row">
    <div class="col">
        <p class="card-text mb-2 ml-1">
            "<%= recent_review.comment %>"
            <br />
            <%= link_to recent_review.movie_title, movie_path(recent_review.movie_id), class: "text-white" %>
        </p>
    </div>
    <div class="col ml-auto">
        <% (1..5).each do |i| %>
            <% if recent_review.rating >= i %>
                <%= image_tag "star-filled.png", size: '20x20', class: "m-0 p-0 mb-2" %>
            <% else %>
                <%= image_tag "star-empty.png", size: '20x20', class: "m-0 p-0 mb-2" %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/home/_review.html.erb
 <div class="row">
    <div class="col-4">
        <% (1..5).each do |i| %>
            <% if review.rating >= i %>
                <%= image_tag "star-filled.png", size: '20x20', class: "m-0 p-0 mb-3" %>
            <% else %>
                <%= image_tag "star-empty.png", size: '20x20', class: "m-0 p-0 mb-3" %>
            <% end %>
        <% end %>
    </div>
    <div class="col">
        <p class="card-text mb-3">
            <% if review.comment != '' and review.comment != nil %>
                "<%= review.comment %>" -
            <% end %>
            <%= review.email %>
        </p>
    </div>
</div>

app/views/home/about.html.erb
<div class="row align-content-center justify-content-center">
    <h1 class="text-muted">About</h1>
</div>

<p>
    This website was written using Ruby on Rails. <br />
    It uses an API provided by The Movie Database to list movies. <br />
    It uses PostgreSQL as its backing database. <br />
</p>

app/views/home/index.html.erb
<div class="row align-content-center justify-content-center">
    <h1 class="text-muted">Movie Spotlight</h1>
</div>
<div class="container">
    <div class="row">
        <div class="col-8">
            <div class="row mt-3">
                <h5 class='font-weight-bold text-secondary my-auto'>Order By: </h5>
                <div class="btn-group ml-3" role="group" aria-label="order by">
                    <button type="button" class="btn btn-secondary movie-control" id="title-button">Title</button>
                    <button type="button" class="btn btn-secondary movie-control" id="release-button">Release Date</button>
                    <button type="button" class="btn btn-secondary movie-control" id="genre-button">Genre</button>
                    <button type="button" class="btn btn-secondary movie-control" id="popularity-button">Popularity</button>
                </div>
                <div class='form-group my-auto ml-3'>
                    <select class="btn btn-secondary" id='genre-select'>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-8">
            <div id="movie-cards">
                <div id="movie-list"></div>            
            </div>
        </div>
        <div class="col-4">
            <div class="card text-white bg-secondary mt-2">
                <h5 class="card-title">Recent Reviews</h5>
                <%= render partial: "recent_review", collection: @recent_reviews %>
                <%= link_to "View All Reviews", reviews_path, class: "text-white ml-auto mr-1 mb-1" %>
            </div>
            <div class="card text-white bg-secondary mt-3">
                <h5 class="card-title">Recent Movies</h5>
                <%= render partial: "recent_movie", collection: @recent_movies %>
                <%= link_to "View All Movies", movies_path, class: "text-white ml-auto mr-1 mb-1" %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Reviews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
      <div class="navbar-brand mr-auto">Movie Reviews</div>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item navbar-text mr-2"><%= link_to_unless_current "Home", home_index_path %></li>
        <li class="nav-item navbar-text mr-2"><%= link_to_unless_current "Movies", movies_path %></li>
        <li class="nav-item navbar-text mr-2"><%= link_to_unless_current "Reviews", reviews_path %></li>
        <li class="nav-item navbar-text"><%= link_to_unless_current "About", about_path %></li>
      </ul>
    </nav>
    <div style="padding-top: 60px; padding-bottom: 50px">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" role="alert">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <nav class="navbar fixed-bottom navbar-dark bg-dark p-1">
      <div class="ml-auto text-light" style="font-size: 14px">
        <%= image_tag "tmdb.svg", size: '25x25', class: 'p-0 m-0' %>
        This product uses the TMDb API but is not endorsed or certified by TMDb.
      </div>
    </nav>
  </body>
</html>

app/views/movies/_review.html.erb
<div class="card text-white bg-secondary mt-3 mx-4 px-4">
    <div class="card-body">
        <p class="card-text">
            <div class="row align-items-center justify-content-center">
                    <% (1..5).each do |i| %>
                        <% if review.rating >= i %>
                            <%= image_tag "star-filled.png", size: '30x30', class: "m-0 p-0 mb-3" %>
                        <% else %>
                            <%= image_tag "star-empty.png", size: '30x30', class: "m-0 p-0 mb-3" %>
                        <% end %>
                    <% end %>
            </div>
            <div class="row align-items-center justify-content-center">
                    <p class="card-text mb-3">
                        <% if review.comment != '' and review.comment != nil %>
                            "<%= review.comment %>" -
                        <% end %>
                        <%= review.email %>
                    </p>
            </div>
        </p>
    </div>
</div>

app/views/movies/index.html.erb
<div class="row align-content-center justify-content-center">
    <h1 class="text-muted">Movie Search</h1>
</div>
<div class="row align-content-center justify-content-center">
    <div class="col-6">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Movie Title" id="search-field">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="search-button">Search</button>
            </div>
        </div>
    </div>
</div>
<div id='search-results'></div>

<div class="row  align-items-center justify-content-center">
    <div class="btn-group" role="group" aria-label="order by">
        <button type="button" class="btn btn-secondary" id="first-button">First</button>
        <button type="button" class="btn btn-secondary" id="previous-button">Previous</button>
        <button type="button" class="btn btn-secondary" disabled="true" id="current-page">1</button>
        <button type="button" class="btn btn-secondary" id="next-button">Next</button>
        <button type="button" class="btn btn-secondary" id="last-button">Last</button>
    </div>
</div>

app/views/movies/show.html.erb
<div id="movie-show-id" movie=<%= @movie_id%>></div>

<%= render partial: "review", collection: @reviews %>

app/views/reviews/_review.html.erb
<div class="card text-white bg-secondary mt-3 mx-4 px-4">
    <div class="card-body">
        <div class="row">
            <%= link_to review.movie_title, movie_path(:id => review.movie_id), class: "mx-auto h2 text-white" %>
        </div>
        <p class="card-text">
            <div class="row align-items-center justify-content-center">
                <% (1..5).each do |i| %>
                    <% if review.rating >= i %>
                        <%= image_tag "star-filled.png", size: '30x30', class: "m-0 p-0 mb-3" %>
                    <% else %>
                        <%= image_tag "star-empty.png", size: '30x30', class: "m-0 p-0 mb-3" %>
                    <% end %>
                <% end %>
            </div>
            <div class="row align-items-center justify-content-center">
                <p class="card-text mb-3">
                    <% if review.comment != '' and review.comment != nil %>
                        "<%= review.comment %>" -
                    <% end %>
                    <%= review.email %>
                </p>
            </div>
        </p>
    </div>
</div>

app/views/reviews/index.html.erb
<div class="row align-content-center justify-content-center">
    <h1 class="text-muted">Reviews</h1>
</div>
<%= render partial: "review", collection: @reviews %>

app/views/reviews/new.html.erb
<div class="row align-content-center justify-content-center">
    <h1 class="text-muted">Write A Review</h1>
</div>
<div class="row align-content-center justify-content-center">
    <h2 class="text-muted"><%= @movie_title %></h2>
</div>
<div class="form-group m-4">
    <%= form_for @review do |f| %>
        <p>
            <%= f.label :email %><br />
            <%= f.text_field :email, class: 'form-control' %><br />
        </p>
        <p>
            <%= f.label :comment %><br />
            <%= f.text_area :comment, class: 'form-control' %><br />
        </p>
            <%= f.label :rating %><br />
            <div class="form-check-inline">
            <%= f.radio_button :rating, 1, :class => 'form-check-input' %>
            <%= f.label :rating_1, "One Star", :class => 'form-check-label' %>
            </div>
            <div class="form-check-inline">
            <%= f.radio_button :rating, 2, :class => 'form-check-input' %>
            <%= f.label :rating_2, "Two Stars", :class => 'form-check-label' %>
            </div>
            <div class="form-check-inline">
            <%= f.radio_button :rating, 3, :class => 'form-check-input' %>
            <%= f.label :rating_3, "Three Stars", :class => 'form-check-label' %>
            </div>
            <div class="form-check-inline">
            <%= f.radio_button :rating, 4, :class => 'form-check-input' %>
            <%= f.label :rating_4, "Four Stars", :class => 'form-check-label' %>
            </div>
            <div class="form-check-inline">
            <%= f.radio_button :rating, 5, :class => 'form-check-input' %>
            <%= f.label :rating_5, "Five Stars", :class => 'form-check-label' %>
            </div>
            <%= f.hidden_field :movie_id, :value => @movie_id %>
            <%= f.hidden_field :movie_title, :value => @movie_title %>
        <p>
            <%= f.submit "Add Post", class: 'form-control btn-secondary' %>
        </p>
    <% end %>
</div>